config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "matches#new"
  resources :matches, only: [:new, :create, :show, :destroy] do
    member do
      get 'public'
      post 'timer'
    end
    resources :competitors, only: [:new, :create, :edit, :update] do
      resources :scores
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/competitor.rb
class Competitor < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :match, optional: true
  has_one :score, dependent: :destroy

  after_create :create_score
  after_update_commit :broadcast_now

  validates :name, presence: true

  private

  def broadcast_now
    broadcast_update_to(match,
                        target: 'competitor_one_private_details',
                        partial: 'matches/competitor_one/competitor_one_private_details',
                        locals: { match: match })
    broadcast_update_to(match,
                        target: 'competitor_one_public_details',
                        partial: 'matches/competitor_one/competitor_one_public_details',
                        locals: { match: match })
    broadcast_update_to(match,
                        target: 'competitor_two_private_details',
                        partial: 'matches/competitor_two/competitor_two_private_details',
                        locals: { match: match })
    broadcast_update_to(match,
                        target: 'competitor_two_public_details',
                        partial: 'matches/competitor_two/competitor_two_public_details',
                        locals: { match: match })
  end

  def create_score
    Score.create!(competitor: self)
  end
end

app/models/match.rb
class Match < ApplicationRecord
  attr_accessor :competitor_one, :competitor_two

  has_many :competitors, dependent: :destroy

  after_create_commit :create_competitors

  validates :competitor_one, presence: true
  validates :competitor_two, presence: true

  after_update_commit :update_timer

  def competitor_one
    competitors.first
  end

  def competitor_two
    competitors.second
  end

  def update_timer
    return unless start_time_previously_changed?
    broadcast_update_to(self,
                        target: 'timer',
                        partial: 'matches/timer',
                        locals: { start_time: start_time })
  end

  private

    def create_competitors
      return unless competitor_one.present? && competitor_two.present?
      Competitor.create!(name: competitor_one, match: self)
      Competitor.create!(name: competitor_two, match: self)
    end
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :competitor
  has_one :match, through: :competitor
  after_update_commit :broadcast_now

  private
    def broadcast_now
      broadcast_update_to(match,
                          target: 'competitor_one_private',
                          partial: 'matches/competitor_one/competitor_one_private',
                          locals: { match: match })
      broadcast_update_to(match,
                          target: 'competitor_two_private',
                          partial: 'matches/competitor_two/competitor_two_private',
                          locals: { match: match })
      broadcast_update_to(match,
                          target: 'competitor_one_public',
                          partial: 'matches/competitor_one/competitor_one_public',
                          locals: { match: match })
      broadcast_update_to(match,
                          target: 'competitor_two_public',
                          partial: 'matches/competitor_two/competitor_two_public',
                          locals: { match: match })
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/competitors_controller.rb
class CompetitorsController < ApplicationController
  before_action :set_match
  before_action :set_label, only: [:new, :create]

  def new
    @competitor = Competitor.new
  end

  def create
    @competitor = Competitor.new(competitor_params.merge(match: @match))

    respond_to do |format|
      if @competitor.save
        if @match.competitors.size >= 2
          format.html { redirect_to match_path(@match) }
        else
          format.html { redirect_to new_match_competitor_path }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @competitor = Competitor.find(params[:id])
  end

  def update
    @competitor = Competitor.find(params[:id])
    @competitor.update(competitor_params)
  end

  private
    def competitor_params
      params.require(:competitor).permit(:name, :match_id)
    end

    def set_match
      @match = Match.find(params[:match_id])
    end

    def set_label
      if @match.competitors.size == 0
        @competitor_label = "Enter First Competitor's name"
      else
        @competitor_label = "Enter Second Competitor's name"
      end
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :public]
  before_action :update_timer, only: [:timer]


  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to match_path(@match)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def public; end

  def timer; end

  private

    def match_params
      params.require(:match).permit(:competitor_one, :competitor_two)
    end

    def set_match
     @match = Match.find(params[:id])
    end

    def update_timer
      set_match
      if params[:result].present?
        if params[:result] == "increment"
          @match.start_time += params[:time]
        else
          @match.start_time -= params[:time]
        end
        @match.save
      else # stop button
        @match.start_time = params[:time]
        @match.save
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def test; end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_competitor
  before_action :set_score
  before_action :set_match

  def update
    type = params[:type].to_unsafe_h
    @column = type.keys.first.to_sym
    @value = type.values.first.to_i
    @current_total_point = @score.send(@column)
    calculate_score
  end

  private
    def score_params
      params.require(:score).permit(:point, :advantage, :penalty, :type)
    end

    def set_competitor
      @competitor = Competitor.find(params[:competitor_id])
    end

    def set_score
      @score = Score.find(params[:id])
    end

    def set_match
      @match = Match.find(params[:match_id])
    end

    def calculate_score
      if params[:increment] == 'true'
        @current_total_point += @value
        @score.update_attribute(@column, @current_total_point)
      else
        @current_total_point -= @value
        @score.update_attribute(@column, @current_total_point)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def timer(start_time)
    Time.at(start_time / 1000).strftime('%M:%S')
  end
end

app/views/competitors/_form.html.erb
<%= form_with model: competitor, url: match_competitors_path, method: :post do |form| %>
  <% if competitor.errors.any? %>
    <div class="bg-yellow-700 rounded p-2 mb-4">
      <p class="text-2xl font-semibold mb-2 text-white">There was a problem</p>
      <ul>
        <% competitor.errors.each do |msg| %>
          <a class="underline hover:no-underline text-white" href="#<%= msg.attribute.to_s %>">
            <li class="text-2xl text-white"><%= msg.full_message %></li>
          </a>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= content_tag("p", competitor_label, class: "text-2xl text-center text-white") %><br>
  <%= form.text_field :name, class: 'border bg-white h-32 rounded p-2 text-4xl w-full text-center' %><br>
  <%= form.button class: "shadow bg-blue-600 hover:bg-blue-700 text-5xl text-white p-8 rounded w-full" do %>
    <span class="show-when-enabled">Save</span>
    <span class="show-when-disabled">Saving...</span>
  <% end %>
<% end %>

app/views/competitors/_inline_form.html.erb
<%= form_with model: competitor, url: match_competitor_path, method: :patch do |form| %>
  <%= form.text_field :name, class: "border-b text-7xl text-white bg-transparent w-full focus:outline-none focus:text-white" %>
  <div class="flex items-center mt-4 space-x-4">
    <%= form.button class: "text-2xl text-white rounded px-4 pt-2 pb-1 border hover:bg-gray-800 text-center" do %>
      <span class="show-when-enabled -ml-1">Save</span>
      <span class="show-when-disabled">Saving...</span>
    <% end %>
    <%= link_to 'Cancel', match_path(competitor.match), class: "text-xl underline hover:no-underline" ,data: { turbo_frame: '_top' } %>
  </div>
<% end %>

app/views/competitors/edit.html.erb
<%= turbo_frame_tag dom_id(@competitor) do %>
  <%= render partial: 'inline_form', locals: { competitor: @competitor } %>
<% end %>

app/views/competitors/new.html.erb
<div class="min-h-screen max-w-4xl mx-auto">
  <section class='flex flex-col justify-center w-full min-h-screen'>
    <%= render 'form', locals: { competitor: @competitor } %>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BjjScoreboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="flex flex-col min-h-screen bg-gray-900 antialiased">
    <main class="flex-1">
      <%= yield %>
    </main>
  </body>
</html>

app/views/matches/_timer.html.erb
<%= timer(start_time) %>

app/views/matches/competitor_one/_competitor_one_private.html.erb
<div class="flex w-full min-h-full text-white">
  <div class="bg-gradient-to-b from-green-500 to-green-700 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl"><%= match.competitor_one.score.point %></span>
    <div class="absolute left-1 top-12">
      <div class="flex flex-col space-y-3">
        <%= button_to match_competitor_score_path(match, match.competitor_one, match.competitor_one.score),
                      method: :patch,
                      params: { type: { point: 2 }, increment: false },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          -2
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_one, match.competitor_one.score),
                      method: :patch,
                      params: { type: { point: 3 }, increment: false },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          -3
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_one, match.competitor_one.score),
                      method: :patch,
                      params: { type: { point: 4 }, increment: false },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          -4
        <% end %>
      </div>
    </div>
    <div class="absolute right-1 top-12">
      <div class="flex flex-col space-y-3">
        <%= button_to match_competitor_score_path(match, match.competitor_one, match.competitor_one.score),
                      method: :patch,
                      params: { type: { point: 2 }, increment: true },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          +2
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_one, match.competitor_one.score),
                      method: :patch,
                      params: { type: { point: 3 }, increment: true },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          +3
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_one, match.competitor_one.score),
                      method: :patch,
                      params: { type: { point: 4 }, increment: true },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          +4
        <% end %>
      </div>
    </div>
  </div>
  <div class="bg-gradient-to-b from-yellow-500 to-yellow-600 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl"><%= match.competitor_one.score.advantage %></span>
    <div class="absolute bottom-1">
      <div class="flex justify-center items-center space-x-10">
        <%= button_to match_competitor_score_path(match, match.competitor_one, match.competitor_one.score),
                      method: :patch,
                      params: { type: { advantage: 1 }, increment: false },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          -1
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_one, match.competitor_one.score),
                      method: :patch,
                      params: { type: { advantage: 1 }, increment: true },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          +1
        <% end %>
      </div>
    </div>
  </div>
  <div class="bg-gradient-to-b from-red-500 to-red-700 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl"><%= match.competitor_one.score.penalty %></span>
    <div class="absolute bottom-1">
      <div class="flex justify-center items-center space-x-10">
        <%= button_to match_competitor_score_path(match, match.competitor_one, match.competitor_one.score),
                      method: :patch,
                      params: { type: { penalty: 1 }, increment: false },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          -1
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_one, match.competitor_one.score),
                      method: :patch,
                      params: { type: { penalty: 1 }, increment: true },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          +1
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/matches/competitor_one/_competitor_one_private_details.html.erb
<%= turbo_frame_tag dom_id(match.competitor_one) do %>
  <%= match.competitor_one.name %>
  <%= link_to 'Edit name', edit_match_competitor_path(match, match.competitor_one), class: "text-white underline hover:no-underline text-xl" %>
<% end %>

app/views/matches/competitor_one/_competitor_one_public.html.erb
<div class="flex w-full min-h-full text-white">
  <div class="pt-12 bg-gradient-to-b from-green-500 to-green-700 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl -ml-6"><%= match.competitor_one.score.point %></span>
  </div>
  <div class="pt-12 bg-gradient-to-b from-yellow-500 to-yellow-600 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl -ml-6"><%= match.competitor_one.score.advantage %></span>
  </div>
  <div class="pt-12 bg-gradient-to-b from-red-500 to-red-700 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl -ml-6"><%= match.competitor_one.score.penalty %></span>
  </div>
</div>

app/views/matches/competitor_one/_competitor_one_public_details.html.erb
<%= match.competitor_one.name %>

app/views/matches/competitor_two/_competitor_two_private.html.erb
<div class="flex w-full min-h-full text-white">
  <div class="bg-gradient-to-t from-green-500 to-green-700 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl"><%= match.competitor_two.score.point %></span>
    <div class="absolute left-1 top-12">
      <div class="flex flex-col space-y-3">
        <%= button_to match_competitor_score_path(match, match.competitor_two, match.competitor_two.score),
                      method: :patch,
                      params: { type: { point: 2 }, increment: false },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          -2
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_two, match.competitor_two.score),
                      method: :patch,
                      params: { type: { point: 3 }, increment: false },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          -3
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_two, match.competitor_two.score),
                      method: :patch,
                      params: { type: { point: 4 }, increment: false },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          -4
        <% end %>
      </div>
    </div>
    <div class="absolute right-1 top-12">
      <div class="flex flex-col space-y-3">
        <%= button_to match_competitor_score_path(match, match.competitor_two, match.competitor_two.score),
                      method: :patch,
                      params: { type: { point: 2 }, increment: true },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          +2
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_two, match.competitor_two.score),
                      method: :patch,
                      params: { type: { point: 3 }, increment: true },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          +3
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_two, match.competitor_two.score),
                      method: :patch,
                      params: { type: { point: 4 }, increment: true },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          +4
        <% end %>
      </div>
    </div>
  </div>
  <div class="bg-gradient-to-t from-yellow-500 to-yellow-600 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl"><%= match.competitor_two.score.advantage %></span>
    <div class="absolute bottom-1">
      <div class="flex justify-center items-center space-x-10">
        <%= button_to match_competitor_score_path(match, match.competitor_two, match.competitor_two.score),
                      method: :patch,
                      params: { type: { advantage: 1 }, increment: false },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          -1
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_two, match.competitor_two.score),
                      method: :patch,
                      params: { type: { advantage: 1 }, increment: true },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          +1
        <% end %>
      </div>
    </div>
  </div>
  <div class="bg-gradient-to-t from-red-500 to-red-700 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl"><%= match.competitor_two.score.penalty %></span>
    <div class="absolute bottom-1">
      <div class="flex justify-center items-center space-x-10">
        <%= button_to match_competitor_score_path(match, match.competitor_two, match.competitor_two.score),
                      method: :patch,
                      params: { type: { penalty: 1 }, increment: false },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          -1
        <% end %>
        <%= button_to match_competitor_score_path(match, match.competitor_two, match.competitor_two.score),
                      method: :patch,
                      params: { type: { penalty: 1 }, increment: true },
                      class: "bg-blue-600 text-lg hover:bg-gray-800 rounded p-4 text-white font-action" do %>
          +1
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/matches/competitor_two/_competitor_two_private_details.html.erb
<%= turbo_frame_tag dom_id(match.competitor_two) do %>
  <%= match.competitor_two.name %>
  <%= link_to 'Edit name',
              edit_match_competitor_path(match, match.competitor_two),
              class: "text-white underline hover:no-underline text-xl" %>
<% end %>

app/views/matches/competitor_two/_competitor_two_public.html.erb
<div class="flex w-full min-h-full text-white">
  <div class="pt-12 bg-gradient-to-t from-green-500 to-green-700 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl -ml-6"><%= match.competitor_two.score.point %></span>
  </div>
  <div class="pt-10 bg-gradient-to-t from-yellow-500 to-yellow-600 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl -ml-6"><%= match.competitor_two.score.advantage %></span>
  </div>
  <div class="pt-10 bg-gradient-to-t from-red-500 to-red-700 flex items-center justify-center flex-1 text-shadow relative">
    <span class="text-12xl -ml-6"><%= match.competitor_two.score.penalty %></span>
    </div>
  </div>
</div>

app/views/matches/competitor_two/_competitor_two_public_details.html.erb
<%= match.competitor_two.name %>

app/views/matches/new.html.erb
  <%= form_with model: @match, url: matches_path, method: :post do |form| %>
    <div class="max-w-2xl mx-auto min-h-screen pt-32 px-2">

      <% if @match.errors.any? %>
        <div class="bg-yellow-700 rounded p-2 mb-4">
          <p class="text-2xl font-semibold mb-2 text-white">There was a problem</p>
          <ul>
            <% @match.errors.each do |msg| %>
              <a class="underline hover:no-underline text-white" href="#<%= msg.attribute.to_s %>">
                <li class="text-2xl text-white"><%= msg.full_message %></li>
              </a>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="text-center">
        <%= form.label "Please enter competitor one's name", class: "text-white text-xl" %>
        <%= form.text_field :competitor_one, class: 'border bg-white h-32 rounded p-2 text-4xl w-full text-center' %>
      </div>
      <div class="text-center mt-4">
        <%= form.label "Please enter competitor two's name", class: "text-white text-xl" %>
        <%= form.text_field :competitor_two, class: 'border bg-white h-32 rounded p-2 text-4xl w-full text-center' %>
      </div>
      <%= form.button class: "shadow bg-blue-600 hover:bg-blue-700 text-4xl text-white p-8 rounded w-full mt-8" do %>
        <span class="show-when-enabled">Save</span>
        <span class="show-when-disabled">Saving...</span>
      <% end %>
      </div>

  <% end %>

  <%#= button_to "Create a match",
                matches_path,
                method: :post,
                class: "shadow bg-blue-600 hover:bg-blue-700 text-5xl text-white p-8 rounded" %>

app/views/matches/public.html.erb
<%= turbo_stream_from @match %>
<section class="flex flex-col min-h-screen font-snes" id="scores">
  <div class="bg-blue-600 flex-1 w-full flex items-stretch">
    <div class="grid grid-cols-12 w-full min-h-full">
      <div class="col-span-5 bg-gradient-to-b from-blue-500 to-blue-700 p-10">
        <div class="flex items-center min-h-full text-white text-8xl text-shadow" id="competitor_one_public_details">
          <%= render partial: 'matches/competitor_one/competitor_one_public_details',
                     locals: { match: @match } %>
        </div>
      </div>
      <div class="col-span-7 bg-black" id="competitor_one_public">
        <%= render partial: "matches/competitor_one/competitor_one_public",
                   locals: { match: @match } %>
      </div>
    </div>
  </div>
  <div class="bg-gray-600 flex-1 w-full flex items-stretch border-t">
    <div class="grid grid-cols-12 w-full min-h-full">
      <div class="col-span-5 bg-gradient-to-b from-gray-500 to-gray-700 p-10">
        <div class="flex items-center min-h-full text-white text-8xl text-shadow" id="competitor_two_public_details">
          <%= render partial: "matches/competitor_two/competitor_two_public_details",
                     locals: { match: @match } %>
        </div>
      </div>
      <div class="col-span-7 bg-black" id="competitor_two_public">
        <%= render partial: 'matches/competitor_two/competitor_two_public',
                   locals: { match: @match } %>
      </div>
    </div>
  </div>
  <div class="bg-black flex-1 w-full p-5 flex justify-center items-center text-white text-12xl relative font-action" id="timer">
    <%= render partial: 'timer', locals: { start_time: @match.start_time } %>
  </div>
</section>

app/views/matches/show.html.erb
<%= turbo_stream_from @match %>
<section class="flex flex-col min-h-screen font-snes" id="scores">
  <div class="bg-blue-600 flex-1 w-full flex items-stretch">
    <div class="grid grid-cols-12 w-full min-h-full">
      <div class="col-span-5 bg-gradient-to-b from-blue-500 to-blue-700 p-10">
        <div class="flex items-center min-h-full text-white text-8xl" id="competitor_one_private_details">
          <%= turbo_frame_tag dom_id(@match.competitor_one) do %>
            <%= render partial: "matches/competitor_one/competitor_one_private_details",
                       locals: { match: @match } %>
          <% end %>
        </div>
      </div>
      <div class="col-span-7 bg-black" id="competitor_one_private">
        <%= render partial: "matches/competitor_one/competitor_one_private",
                   locals: { match: @match } %>
      </div>
    </div>
  </div>
  <div class="bg-gray-600 flex-1 w-full flex items-stretch border-t">
    <div class="grid grid-cols-12 w-full min-h-full">
      <div class="col-span-5 bg-gradient-to-b from-gray-500 to-gray-700 p-10">
        <div class="flex items-center min-h-full text-white text-8xl" id="competitor_two_private_details">
          <%= turbo_frame_tag dom_id(@match.competitor_two) do %>
            <%= render partial: "matches/competitor_two/competitor_two_private_details",
                       locals: { match: @match } %>
          <% end %>
        </div>
      </div>
      <div class="col-span-7 bg-black" id="competitor_two_private">
        <%= render partial: "matches/competitor_two/competitor_two_private",
                   locals: { match: @match } %>
      </div>
    </div>
  </div>
  <div class="bg-black flex-1 w-full p-5 flex justify-center items-center text-white text-12xl relative font-action" data-controller="timer">
    <div id="timer">
      <%= render partial: 'timer', locals: { start_time: @match.start_time } %>
    </div>
    <div class="absolute bottom-1 left-0 right-0 text-xl">
      <div class="flex space-x-4 px-1">
        <button class="bg-blue-600 hover:bg-gray-800 rounded p-4 text-white timer-actions"
                data-action="click->timer#updateTimer"
                data-timer-url-param="<%= timer_match_path(@match).gsub('.','/') %>"
                data-timer-time-param="60000"
                data-timer-result-param="increment">
        +1 min
        </button>
        <button class="bg-blue-600 hover:bg-gray-800 rounded p-4 text-white timer-actions"
                data-action="click->timer#updateTimer"
                data-timer-url-param="<%= timer_match_path(@match).gsub('.','/') %>"
                data-timer-time-param="60000"
                data-timer-result-param="decrement"
        >
        -1 min</button>
        <button class="bg-blue-600 hover:bg-gray-800 rounded p-4 text-white timer-actions"
                data-action="click->timer#updateTimer"
                data-timer-url-param="<%= timer_match_path(@match).gsub('.','/') %>"
                data-timer-time-param="1000"
                data-timer-result-param="increment"
        >
        +1 sec</button>
        <button class="bg-blue-600 hover:bg-gray-800 rounded p-4 text-white timer-actions"
                data-action="click->timer#updateTimer"
                data-timer-url-param="<%= timer_match_path(@match).gsub('.','/') %>"
                data-timer-time-param="1000"
                data-timer-result-param="decrement"
        >
        -1 sec</button>
      </div>
    </div>
    <div class="absolute bottom-1 right-0 text-xl">
      <div class="flex space-x-4 px-1">
        <button class="bg-blue-600 hover:bg-gray-800 rounded p-4 play-actions"
                id="play"
                data-action="click->timer#play"
                data-timer-url-param="<%= timer_match_path(@match).gsub('.','/') %>">
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-play-fill" viewBox="0 0 16 16">
            <path d="m11.596 8.697-6.363 3.692c-.54.313-1.233-.066-1.233-.697V4.308c0-.63.692-1.01 1.233-.696l6.363 3.692a.802.802 0 0 1 0 1.393z"/>
          </svg>
        </button>
        <button class="bg-blue-600 hover:bg-gray-800 rounded p-4 play-actions"
                id="stop"
                data-action="click->timer#stop"
                data-timer-url-param="<%= timer_match_path(@match).gsub('.','/') %>">
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-stop-fill" viewBox="0 0 16 16">
            <path d="M5 3.5h6A1.5 1.5 0 0 1 12.5 5v6a1.5 1.5 0 0 1-1.5 1.5H5A1.5 1.5 0 0 1 3.5 11V5A1.5 1.5 0 0 1 5 3.5z"/>
          </svg>
        </button>
        <button class="bg-blue-600 hover:bg-gray-800 rounded p-4 play-actions"
                id="restart"
                data-action="click->timer#restart"
                data-timer-url-param="<%= timer_match_path(@match).gsub('.','/') %>">
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-counterclockwise" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 3a5 5 0 1 1-4.546 2.914.5.5 0 0 0-.908-.417A6 6 0 1 0 8 2v1z"/>
            <path d="M8 4.466V.534a.25.25 0 0 0-.41-.192L5.23 2.308a.25.25 0 0 0 0 .384l2.36 1.966A.25.25 0 0 0 8 4.466z"/>
          </svg>
        </button>
      </div>
    </div>
  </div>
</section>